data:
  train_bs: 1
  # train_width: 576 
  # train_height: 1024
  train_width: 512 
  train_height: 640
  meta_paths:
    - "dataset/data/TikTok_meta.json"
  sample_rate: 4 
  n_sample_frames: 16

control_stage_config:
  image_size: 32 # unused
  in_channels: 4
  hint_channels: 3
  model_channels: 320
  attention_resolutions: [ 4, 2, 1 ]
  num_res_blocks: 2
  channel_mult: [ 1, 2, 4, 4 ]
  num_heads: 8
  use_spatial_transformer: True
  transformer_depth: 1
  context_dim: 768
  use_checkpoint: True
  legacy: False

solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: True 
  gradient_checkpointing: True 
  max_train_steps: 10000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1e-5
  scale_lr: False 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

val:
  validation_steps: 800

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "linear"
  steps_offset:        1
  clip_sample:         false

num_inference_steps: 25 
do_classifier_free_guidance: True 
base_model_path: 'models/SVD/stable-video-diffusion-img2vid-xt-1-1'
ckpt_path: 'models/MimicMotion.pth'
vae_model_path: './pretrained_weights/sd-vae-ft-mse'
image_encoder_path: './pretrained_weights/sd-image-variations-diffusers/image_encoder'
mm_path: './pretrained_weights/mm_sd_v15_v2.ckpt'

weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True 
stage1_ckpt_dir: 'models/MimicMotion.pth'
stage1_ckpt_step: 980

seed: 42
resume_from_checkpoint: ''
checkpointing_steps: 200
exp_name: 'stage2'
output_dir: './exp_output' 

clip_version: 'openai/clip-vit-large-patch14' 
a_prompt: 'realistic, best quality, extremely detailed'
n_prompt: 'fake 3D rendered image, longbody, lowres, bad anatomy, bad hands, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, blue'